'use strict';

// Generates a simple per-prospect pitch PDF (PRD §5.8 / §9.2 "Generate pitch PDF").
// Uses pdfkit (already a dependency, see rxPdfBuilder). Returns a Buffer the route
// uploads to S3. Keep it lightweight — a branded cover + prospect details + a few
// value-prop bullet points pulled from the request / pitch template_json.

const PDFDocument = require('pdfkit');

const DEFAULT_POINTS = [
  'All-in-one clinic OS: scheduling, records, billing & inventory',
  'Specialty workflows: ortho, implant, endo, paedo, TMJ',
  'WhatsApp-first patient engagement & marketing',
  'Multi-clinic, role-based access with full audit trail',
  'Go-live in days with guided data migration & training',
];

function buildPitchPdf({ clinicName, contactName, city, title, points } = {}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 56 });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header band
      doc.rect(0, 0, doc.page.width, 120).fill('#6d28d9');
      doc.fillColor('#ffffff').fontSize(26).text('DentaFlow', 56, 44);
      doc.fontSize(12).fillColor('#ede9fe').text('Clinic Operating System', 56, 80);

      doc.moveDown(4);
      doc.fillColor('#0f172a').fontSize(20).text(title || 'Partnership Proposal', 56, 150);

      // Prospect block
      doc.moveDown(1).fontSize(12).fillColor('#334155');
      doc.text(`Prepared for: ${clinicName || 'Your clinic'}`);
      if (contactName) doc.text(`Attention: ${contactName}`);
      if (city) doc.text(`Location: ${city}`);
      doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`);

      // Value points
      doc.moveDown(1.5).fontSize(14).fillColor('#6d28d9').text('Why DentaFlow');
      doc.moveDown(0.5).fontSize(11.5).fillColor('#334155');
      for (const p of (Array.isArray(points) && points.length ? points : DEFAULT_POINTS)) {
        doc.circle(64, doc.y + 6, 2).fill('#6d28d9');
        doc.fillColor('#334155').text(p, 76, doc.y - 6);
        doc.moveDown(0.4);
      }

      doc.moveDown(2).fontSize(10).fillColor('#94a3b8')
        .text('This proposal was auto-generated by the DentaFlow marketing console.', 56, doc.page.height - 90, { width: doc.page.width - 112 });

      doc.end();
    } catch (err) { reject(err); }
  });
}

module.exports = { buildPitchPdf };
